### ISSUE TITLE
Not identifying all pairs properly, and it doesn't appear to be scoring No Formation hands.

### ISSUE THREAD

**Issue by Taegost** [Anders-H/GenericPokerFormationChecker#1]
Sample hands from three instances of the FormationChecker:
Hand 1 - {FORMATION=NOTHING,SCORE=0000,HAND=SPD06-DMN10-DMN09-DMNAC-DMN06}
Hand 2 - {FORMATION=NOTHING,SCORE=0000,HAND=CLBQU-SPD09-DMN09-DMNAC-DMN06}
Hand 3 - {FORMATION=NOTHING,SCORE=0000,HAND=CLBKI-DMNKI-HRTKI-HRTQU-DMN02}

Both hands 1 and 2 should have been identified as a Pair (6 of Diamond and Spades for hand 1, 9 of Diamonds and Spades for hand 2).
Hand 3 should have been identified as 3 of a kind.
In all cases, none are scored.

**Comment by Taegost** [comment]
> two

**Comment by Taegost** [comment]
I just realized that when I shuffled my code around, I forgot the "CheckFormation" portion.  Seems to be working fine now, sorry for that!

**Comment by Anders-H** [comment]
Thank you!
